#!/bin/bash

BASEDIR="/demo/acmewarehouse"
NODEDIR="$BASEDIR/nodejs-server/"

# Clone the most recent ACMEWarehouse REST Demo and CD into directory
git clone https://github.com/themsquared/APIM-ACMEWarehouse-REST.git "$BASEDIR"
cp "$BASEDIR/nginx-configuration/default" /etc/nginx/sites-available/

cd "$NODEDIR"
service mongodb start
service nginx start

exec nodejs index.js


